github:
  is_project_page: false
theme: jekyll-theme-slate
title: EssentIR
#description: Efficient Self-Supervised Metric Information Retrieval: A Bibliography Based Method Applied to COVID Literature
