github:
  is_project_page: false
theme: jekyll-theme-slate
title: SUBLIMER
description: Efficient Self-Supervised Metric Information Retrieval: A Bibliography Based Method Applied to COVID Literature
